---
 - hosts: all
   become: true
   tasks:
     
     - name: Ensure apt cache is updated.
       apt: update_cache=yes cache_valid_time=3600
     
     - name: Descargar paquetes necesarios para Varnish
       apt:
		name: '{{ item }}' 
		state: 'installed"
       with_items:
       - automake
       - autotools-dev
       - libedit-dev
       - libjemalloc-dev
       - libncurses-dev
       - libpcre3-dev
       - libtool
       - pkg-config
       - python-docutils
       - python-sphinx
       - graphviz
       - git
     
     - name: Crear carpeta descarga Git
       file: 
		path:	/root/varnish-git 
		state:	directory
     
     - name: Giteando  
       git: 
		repo:	'https://github.com/varnishcache/varnish-cache.git'
        dest:	'/root/varnish-git'

     - name: Running  Configure for Varnish-Git
          shell: ./configure --prefix=/usr/local/varnish-master 
          args:
			chdir: /root/varnish-git/

     - name: Running  autogen.sh for Varnish-Git
          shell: autogen.sh
          args:
			chdir: /root/varnish-git/


     - name: Running  make for Varnish-Git
          shell: make
          args:
			chdir: /root/varnish-git/

     - name: Running  make install for Varnish-Git
          shell: make install
          args:
			chdir: /root/varnish-git/


     - name: Running  make check for Varnish-Git
          shell: make check
          args:
			chdir: /root/varnish-git/
