---
 - hosts: all
   become: true
   tasks:
     - name: Ensure apt cache is updated.
       apt: update_cache=yes cache_valid_time=3600
     - name: Descargar paquetes necesarios para Varnish
       apt: "name={{ item }} state=installed"
       with_items:
       - automake
       - autotools-dev
       - libedit-dev
       - libjemalloc-dev
       - libncurses-dev
       - libpcre3-dev
       - libtool
       - pkg-config
       - python-docutils
       - python-sphinx
       - graphviz
       - git
     - name: Crear carpeta descarga Git
       file: path=/root/varnish-git state=directory
     - name: Giteando  
       git: repo='https://github.com/varnishcache/varnish-cache.git'
            dest='/root/varnish-git'
     - name: Running "Autogen" and "Configure" for Varnish-Git
       script: "chdir=/root/varnish-git/ {{ item }}"
       with_items:
         - autogen.sh
         - configure
     - name: Build Varnish-Git
       command: "chdir=/root/varnish-git/ {{ item }}"'
       with_items:
        - make
        - make check

